.nh
.TH "CIDER" "1" "Oct 2020" "" ""

.SH NAME
.PP
cider \- Submit your builds to the Apple App Store in seconds


.SH SYNOPSIS
.PP
\fBcider [flags]\fP


.SH DESCRIPTION
.PP
Cider  Copyright (C) 2020  Aaron Sky

.PP
This program comes with ABSOLUTELY NO WARRANTY; for details type \fB\fChelp'. 
This is free software, and you are welcome to redistribute it under certain conditions; 
type\fRhelp' for details.


.SH OPTIONS
.PP
\fB\-\-debug\fP[=false]
	Enable debug mode

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for cider


.SH SEE ALSO
.PP
\fBcider\-check(1)\fP, \fBcider\-completions(1)\fP, \fBcider\-docs(1)\fP, \fBcider\-init(1)\fP, \fBcider\-release(1)\fP
