source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "github-pages", "~> 207", group: :jekyll_plugins
gem "jekyll-seo-tag", "~> 2.6"
gem "just-the-docs"
